### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by ghost** [whoozle/btanks#2]
Yay! You're on the list too!
https://github.com/saniv/free-game-art/blob/master/foss-copyright-infringement-records.md
Battle Tanks (https://sourceforge.net/projects/btanks/ https://github.com/whoozle/btanks), "Fun action game, could be found in any linux distro", like other linux games, it claims to be licensed under GPL2 and steals sounds from Sound Ideas 6000. For example, helicopter.ogg is stolen from CD19, track 5, "helicopter bell 206 - int - hovering"

**Comment by whoozle** [comment]
We did not downloaded any sounds from anywhere from the internet, all sounds were made by sound engineering firm and they pay for them, I'll try to find contact and forward your claims to them. 

Moreover, most of the sounds were generated by native instruments (reactor?) software (I'm not sure, it was more than ten years ago). This arises question where did THEY get this sound, how old this CD19, what's your methodology on comparing sounds, and even it's from CD19, why do you think we can't use the sound we've bought for money?

**Comment by whoozle** [comment]
answered you in your repo
https://github.com/saniv/free-game-art/issues/3
