### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [whoozle/btanks#3]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/114332662-3a83db00-9b79-11eb-910e-9489999b002e.png)

thank you  
best regards to you  
William

**Comment by whoozle** [comment]
Hello, William
Please run 
```
git pull
git submodules update
```

I brushed up cmake support a bit and update clunk library too. Should be fine now (pow10f was removed from glibc)

**Comment by WilliamWangPeng** [comment]
> Hello, William
> Please run
> 
> ```
> git pull
> git submodules update
> ```
> 
> I brushed up cmake support a bit and update clunk library too. Should be fine now (pow10f was removed from glibc)

hi dear @whoozle   

  
![image](https://user-images.githubusercontent.com/51076736/114562377-0a375c00-9ca1-11eb-96bd-c592a8182c41.png)   

![image](https://user-images.githubusercontent.com/51076736/114562593-36eb7380-9ca1-11eb-9de8-efc2a7106661.png)  

![image](https://user-images.githubusercontent.com/51076736/114562717-55ea0580-9ca1-11eb-9a63-5a4d6cbd8c55.png)  
 still doesn't work.

**Comment by whoozle** [comment]
I've just made smpeg optional, remove build directory and start again please. 
List of the required dependencies is in README-linux.txt

**Comment by whoozle** [comment]
anything else I can help you with? Feel free to reopen if it's still failing
